project:
  type: website
  output-dir: _site

website:
  title: "pins for Python"
  description: "Pin, Discover, and Share Resources"
  page-navigation: true
  favicon: "favicon.ico"
  page-footer:
    center: |
      Proudly supported by
      [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit PBC" width=65px}](https://posit.co/)
  navbar:
    background: light
    pinned: true
    logo: logo.png
    left:
      - text: "Get started"
        file: get_started.qmd
      - text: "Function reference"
        file: reference/index.qmd
      - text: Learn more
        menu:
          - text: "Create consistent metadata for pins"
            file: customize-pins-metadata.qmd
          - text: "pins for R"
            href: https://pins.rstudio.com
            target: _blank
    right:
      - icon: github
        href: https://github.com/rstudio/vetiver-python
        aria-label: Vetiver python GitHub

  sidebar:
    - id: function-reference
      title: Get Started
      collapse-level: 2
      style: "floating"
      align: left
      contents:
        - href: get-started/index.qmd
        - href: get-started/version.qmd
        - href: get-started/deploy.qmd
        - href: get-started/monitor.qmd

    - id: learn-more
      title: Learn More
      collapse-level: 3
      align: left
      contents:
        - href: learn-more/parity-checklist.qmd
        - href: learn-more/model-card.qmd
        - href: learn-more/deploy-with-docker.qmd

quartodoc:
  package: pins
  sidebar: "_sidebar.yml"
  sections:
    - title: Boards
      desc: ""
      contents:
        - board_folder
        - board_local
        - board_temp
        - board_s3
        - board_gcs
        - board_azure
        - board_connect
        - board_url
        - board
    - title: Pins
      desc: ""
      package: pins.boards.BaseBoard
      contents:
        - pin_read
        - pin_write
        - pin_meta
        - pin_download
        - pin_upload
        - pin_versions
        - pin_list
        - pin_exists
        - pin_version_delete
        - pin_versions_prune
        - pin_delete
        - pin_search

metadata-files:
  - _sidebar.yml

filters:
  - interlinks

interlinks:
  sources: {}
